from enum import Enum

class SearchState(str, Enum):
    IDLE = "IDLE"
    TARGET_READY = "TARGET_READY"
    SEARCHING = "SEARCHING"
    CANDIDATE_DETECTED = "CANDIDATE_DETECTED"
    VERIFYING = "VERIFYING"
    GUIDING = "GUIDING"
    FOUND = "FOUND"
    SEARCH_COMPLETE = "SEARCH_COMPLETE"
